/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.thomas.client;

import javax.swing.ImageIcon;

/**
 *
 * @author LongJing
 */
public class SelectDialog extends javax.swing.JDialog {

	private static final long serialVersionUID = 5554648709567200426L;
	private Boolean isButtonSelect1 = false;
	private Boolean isButtonSelect10 = false;
	private Boolean isButtonSelect11 = false;
	private Boolean isButtonSelect12 = false;
	private Boolean isButtonSelect13 = false;
	private Boolean isButtonSelect14 = false;
	private Boolean isButtonSelect15 = false;
	private Boolean isButtonSelect16 = false;
	private Boolean isButtonSelect17 = false;
	private Boolean isButtonSelect18 = false;
	private Boolean isButtonSelect19 = false;
	private Boolean isButtonSelect2 = false;
	private Boolean isButtonSelect20 = false;
	private Boolean isButtonSelect21 = false;
	private Boolean isButtonSelect22 = false;
	private Boolean isButtonSelect23 = false;
	private Boolean isButtonSelect24 = false;
	private Boolean isButtonSelect25 = false;
	private Boolean isButtonSelect26 = false;
	private Boolean isButtonSelect27 = false;
	private Boolean isButtonSelect28 = false;
	private Boolean isButtonSelect29 = false;
	private Boolean isButtonSelect3 = false;
	private Boolean isButtonSelect30 = false;
	private Boolean isButtonSelect31 = false;
	private Boolean isButtonSelect32 = false;
	private Boolean isButtonSelect33 = false;
	private Boolean isButtonSelect34 = false;
	private Boolean isButtonSelect35 = false;
	private Boolean isButtonSelect36 = false;
	private Boolean isButtonSelect37 = false;
	private Boolean isButtonSelect38 = false;
	private Boolean isButtonSelect39 = false;
	private Boolean isButtonSelect4 = false;
	private Boolean isButtonSelect40 = false;
	private Boolean isButtonSelect41 = false;
	private Boolean isButtonSelect42 = false;
	private Boolean isButtonSelect43 = false;
	private Boolean isButtonSelect44 = false;
	private Boolean isButtonSelect5 = false;
	private Boolean isButtonSelect6 = false;
	private Boolean isButtonSelect7 = false;
	private Boolean isButtonSelect8 = false;
	private Boolean isButtonSelect9 = false;
	
	private ConfigDialog parent = null;
	private int type = 1;

	/**
	 * Creates new form SelectDialog
	 */
	public SelectDialog(ConfigDialog parent, boolean modal, int type) {
		super(parent, modal);
		this.parent = parent;
		initComponents();
        setLocationRelativeTo(null);
		this.type = type;
		if (type == 1) {
			initdata(parent.自选花牌);
		} else {
			initdata(parent.自选财神);
		}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("牌型选择");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setMinimumSize(new java.awt.Dimension(550, 650));
        jPanel1.setPreferredSize(new java.awt.Dimension(550, 650));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jButton1.setIcon(new ImageIcon("./res/type_1/card_type_down/1.png"));
        jButton1.setMaximumSize(new java.awt.Dimension(45, 60));
        jButton1.setMinimumSize(new java.awt.Dimension(45, 60));
        jButton1.setPreferredSize(new java.awt.Dimension(45, 60));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(6, 3, 6, 3);
        jPanel1.add(jButton1, gridBagConstraints);

        jButton2.setIcon(new ImageIcon("./res/type_1/card_type_down/2.png"));
        jButton2.setMaximumSize(new java.awt.Dimension(45, 60));
        jButton2.setMinimumSize(new java.awt.Dimension(45, 60));
        jButton2.setPreferredSize(new java.awt.Dimension(45, 60));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(6, 3, 6, 3);
        jPanel1.add(jButton2, gridBagConstraints);

        jButton3.setIcon(new ImageIcon("./res/type_1/card_type_down/3.png"));
        jButton3.setMaximumSize(new java.awt.Dimension(45, 60));
        jButton3.setMinimumSize(new java.awt.Dimension(45, 60));
        jButton3.setPreferredSize(new java.awt.Dimension(45, 60));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(6, 3, 6, 3);
        jPanel1.add(jButton3, gridBagConstraints);

        jButton4.setIcon(new ImageIcon("./res/type_1/card_type_down/4.png"));
        jButton4.setMaximumSize(new java.awt.Dimension(45, 60));
        jButton4.setMinimumSize(new java.awt.Dimension(45, 60));
        jButton4.setPreferredSize(new java.awt.Dimension(45, 60));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(6, 3, 6, 3);
        jPanel1.add(jButton4, gridBagConstraints);

        jButton5.setIcon(new ImageIcon("./res/type_1/card_type_down/5.png"));
        jButton5.setMaximumSize(new java.awt.Dimension(45, 60));
        jButton5.setMinimumSize(new java.awt.Dimension(45, 60));
        jButton5.setPreferredSize(new java.awt.Dimension(45, 60));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(6, 3, 6, 3);
        jPanel1.add(jButton5, gridBagConstraints);

        jButton6.setIcon(new ImageIcon("./res/type_1/card_type_down/6.png"));
        jButton6.setMaximumSize(new java.awt.Dimension(45, 60));
        jButton6.setMinimumSize(new java.awt.Dimension(45, 60));
        jButton6.setPreferredSize(new java.awt.Dimension(45, 60));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(6, 3, 6, 3);
        jPanel1.add(jButton6, gridBagConstraints);

        jButton7.setIcon(new ImageIcon("./res/type_1/card_type_down/7.png"));
        jButton7.setMaximumSize(new java.awt.Dimension(45, 60));
        jButton7.setMinimumSize(new java.awt.Dimension(45, 60));
        jButton7.setPreferredSize(new java.awt.Dimension(45, 60));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(6, 3, 6, 3);
        jPanel1.add(jButton7, gridBagConstraints);

        jButton8.setIcon(new ImageIcon("./res/type_1/card_type_down/8.png"));
        jButton8.setMaximumSize(new java.awt.Dimension(45, 60));
        jButton8.setMinimumSize(new java.awt.Dimension(45, 60));
        jButton8.setPreferredSize(new java.awt.Dimension(45, 60));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(6, 3, 6, 3);
        jPanel1.add(jButton8, gridBagConstraints);

        jButton9.setIcon(new ImageIcon("./res/type_1/card_type_down/9.png"));
        jButton9.setMaximumSize(new java.awt.Dimension(45, 60));
        jButton9.setMinimumSize(new java.awt.Dimension(45, 60));
        jButton9.setPreferredSize(new java.awt.Dimension(45, 60));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(6, 3, 6, 3);
        jPanel1.add(jButton9, gridBagConstraints);

        jButton10.setIcon(new ImageIcon("./res/type_1/card_type_down/10.png"));
        jButton10.setMaximumSize(new java.awt.Dimension(45, 60));
        jButton10.setMinimumSize(new java.awt.Dimension(45, 60));
        jButton10.setPreferredSize(new java.awt.Dimension(45, 60));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(6, 3, 6, 3);
        jPanel1.add(jButton10, gridBagConstraints);

        jButton11.setIcon(new ImageIcon("./res/type_1/card_type_down/11.png"));
        jButton11.setMaximumSize(new java.awt.Dimension(45, 60));
        jButton11.setMinimumSize(new java.awt.Dimension(45, 60));
        jButton11.setPreferredSize(new java.awt.Dimension(45, 60));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(6, 3, 6, 3);
        jPanel1.add(jButton11, gridBagConstraints);

        jButton12.setIcon(new ImageIcon("./res/type_1/card_type_down/12.png"));
        jButton12.setMaximumSize(new java.awt.Dimension(45, 60));
        jButton12.setMinimumSize(new java.awt.Dimension(45, 60));
        jButton12.setPreferredSize(new java.awt.Dimension(45, 60));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(6, 3, 6, 3);
        jPanel1.add(jButton12, gridBagConstraints);

        jButton13.setIcon(new ImageIcon("./res/type_1/card_type_down/13.png"));
        jButton13.setMaximumSize(new java.awt.Dimension(45, 60));
        jButton13.setMinimumSize(new java.awt.Dimension(45, 60));
        jButton13.setPreferredSize(new java.awt.Dimension(45, 60));
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(6, 3, 6, 3);
        jPanel1.add(jButton13, gridBagConstraints);

        jButton14.setIcon(new ImageIcon("./res/type_1/card_type_down/14.png"));
        jButton14.setMaximumSize(new java.awt.Dimension(45, 60));
        jButton14.setMinimumSize(new java.awt.Dimension(45, 60));
        jButton14.setPreferredSize(new java.awt.Dimension(45, 60));
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(6, 3, 6, 3);
        jPanel1.add(jButton14, gridBagConstraints);

        jButton15.setIcon(new ImageIcon("./res/type_1/card_type_down/15.png"));
        jButton15.setMaximumSize(new java.awt.Dimension(45, 60));
        jButton15.setMinimumSize(new java.awt.Dimension(45, 60));
        jButton15.setPreferredSize(new java.awt.Dimension(45, 60));
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(6, 3, 6, 3);
        jPanel1.add(jButton15, gridBagConstraints);

        jButton16.setIcon(new ImageIcon("./res/type_1/card_type_down/16.png"));
        jButton16.setMaximumSize(new java.awt.Dimension(45, 60));
        jButton16.setMinimumSize(new java.awt.Dimension(45, 60));
        jButton16.setPreferredSize(new java.awt.Dimension(45, 60));
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(6, 3, 6, 3);
        jPanel1.add(jButton16, gridBagConstraints);

        jButton17.setIcon(new ImageIcon("./res/type_1/card_type_down/17.png"));
        jButton17.setMaximumSize(new java.awt.Dimension(45, 60));
        jButton17.setMinimumSize(new java.awt.Dimension(45, 60));
        jButton17.setPreferredSize(new java.awt.Dimension(45, 60));
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(6, 3, 6, 3);
        jPanel1.add(jButton17, gridBagConstraints);

        jButton18.setIcon(new ImageIcon("./res/type_1/card_type_down/18.png"));
        jButton18.setMaximumSize(new java.awt.Dimension(45, 60));
        jButton18.setMinimumSize(new java.awt.Dimension(45, 60));
        jButton18.setPreferredSize(new java.awt.Dimension(45, 60));
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(6, 3, 6, 3);
        jPanel1.add(jButton18, gridBagConstraints);

        jButton19.setIcon(new ImageIcon("./res/type_1/card_type_down/19.png"));
        jButton19.setMaximumSize(new java.awt.Dimension(45, 60));
        jButton19.setMinimumSize(new java.awt.Dimension(45, 60));
        jButton19.setPreferredSize(new java.awt.Dimension(45, 60));
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(6, 3, 6, 3);
        jPanel1.add(jButton19, gridBagConstraints);

        jButton20.setIcon(new ImageIcon("./res/type_1/card_type_down/20.png"));
        jButton20.setMaximumSize(new java.awt.Dimension(45, 60));
        jButton20.setMinimumSize(new java.awt.Dimension(45, 60));
        jButton20.setPreferredSize(new java.awt.Dimension(45, 60));
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(6, 3, 6, 3);
        jPanel1.add(jButton20, gridBagConstraints);

        jButton21.setIcon(new ImageIcon("./res/type_1/card_type_down/21.png"));
        jButton21.setMaximumSize(new java.awt.Dimension(45, 60));
        jButton21.setMinimumSize(new java.awt.Dimension(45, 60));
        jButton21.setPreferredSize(new java.awt.Dimension(45, 60));
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(6, 3, 6, 3);
        jPanel1.add(jButton21, gridBagConstraints);

        jButton22.setIcon(new ImageIcon("./res/type_1/card_type_down/22.png"));
        jButton22.setMaximumSize(new java.awt.Dimension(45, 60));
        jButton22.setMinimumSize(new java.awt.Dimension(45, 60));
        jButton22.setPreferredSize(new java.awt.Dimension(45, 60));
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(6, 3, 6, 3);
        jPanel1.add(jButton22, gridBagConstraints);

        jButton23.setIcon(new ImageIcon("./res/type_1/card_type_down/23.png"));
        jButton23.setMaximumSize(new java.awt.Dimension(45, 60));
        jButton23.setMinimumSize(new java.awt.Dimension(45, 60));
        jButton23.setPreferredSize(new java.awt.Dimension(45, 60));
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(6, 3, 6, 3);
        jPanel1.add(jButton23, gridBagConstraints);

        jButton24.setIcon(new ImageIcon("./res/type_1/card_type_down/24.png"));
        jButton24.setMaximumSize(new java.awt.Dimension(45, 60));
        jButton24.setMinimumSize(new java.awt.Dimension(45, 60));
        jButton24.setPreferredSize(new java.awt.Dimension(45, 60));
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(6, 3, 6, 3);
        jPanel1.add(jButton24, gridBagConstraints);

        jButton25.setIcon(new ImageIcon("./res/type_1/card_type_down/25.png"));
        jButton25.setMaximumSize(new java.awt.Dimension(45, 60));
        jButton25.setMinimumSize(new java.awt.Dimension(45, 60));
        jButton25.setPreferredSize(new java.awt.Dimension(45, 60));
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(6, 3, 6, 3);
        jPanel1.add(jButton25, gridBagConstraints);

        jButton26.setIcon(new ImageIcon("./res/type_1/card_type_down/26.png"));
        jButton26.setMaximumSize(new java.awt.Dimension(45, 60));
        jButton26.setMinimumSize(new java.awt.Dimension(45, 60));
        jButton26.setPreferredSize(new java.awt.Dimension(45, 60));
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(6, 3, 6, 3);
        jPanel1.add(jButton26, gridBagConstraints);

        jButton27.setIcon(new ImageIcon("./res/type_1/card_type_down/27.png"));
        jButton27.setMaximumSize(new java.awt.Dimension(45, 60));
        jButton27.setMinimumSize(new java.awt.Dimension(45, 60));
        jButton27.setPreferredSize(new java.awt.Dimension(45, 60));
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(6, 3, 6, 3);
        jPanel1.add(jButton27, gridBagConstraints);

        jButton28.setIcon(new ImageIcon("./res/type_1/card_type_down/28.png"));
        jButton28.setMaximumSize(new java.awt.Dimension(45, 60));
        jButton28.setMinimumSize(new java.awt.Dimension(45, 60));
        jButton28.setPreferredSize(new java.awt.Dimension(45, 60));
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(6, 3, 6, 3);
        jPanel1.add(jButton28, gridBagConstraints);

        jButton29.setIcon(new ImageIcon("./res/type_1/card_type_down/29.png"));
        jButton29.setMaximumSize(new java.awt.Dimension(45, 60));
        jButton29.setMinimumSize(new java.awt.Dimension(45, 60));
        jButton29.setPreferredSize(new java.awt.Dimension(45, 60));
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton29ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(6, 3, 6, 3);
        jPanel1.add(jButton29, gridBagConstraints);

        jButton30.setIcon(new ImageIcon("./res/type_1/card_type_down/30.png"));
        jButton30.setMaximumSize(new java.awt.Dimension(45, 60));
        jButton30.setMinimumSize(new java.awt.Dimension(45, 60));
        jButton30.setPreferredSize(new java.awt.Dimension(45, 60));
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(6, 3, 6, 3);
        jPanel1.add(jButton30, gridBagConstraints);

        jButton31.setIcon(new ImageIcon("./res/type_1/card_type_down/31.png"));
        jButton31.setMaximumSize(new java.awt.Dimension(45, 60));
        jButton31.setMinimumSize(new java.awt.Dimension(45, 60));
        jButton31.setPreferredSize(new java.awt.Dimension(45, 60));
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(6, 3, 6, 3);
        jPanel1.add(jButton31, gridBagConstraints);

        jButton32.setIcon(new ImageIcon("./res/type_1/card_type_down/32.png"));
        jButton32.setMaximumSize(new java.awt.Dimension(45, 60));
        jButton32.setMinimumSize(new java.awt.Dimension(45, 60));
        jButton32.setPreferredSize(new java.awt.Dimension(45, 60));
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton32ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(6, 3, 6, 3);
        jPanel1.add(jButton32, gridBagConstraints);

        jButton33.setIcon(new ImageIcon("./res/type_1/card_type_down/33.png"));
        jButton33.setMaximumSize(new java.awt.Dimension(45, 60));
        jButton33.setMinimumSize(new java.awt.Dimension(45, 60));
        jButton33.setPreferredSize(new java.awt.Dimension(45, 60));
        jButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton33ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(6, 3, 6, 3);
        jPanel1.add(jButton33, gridBagConstraints);

        jButton34.setIcon(new ImageIcon("./res/type_1/card_type_down/34.png"));
        jButton34.setMaximumSize(new java.awt.Dimension(45, 60));
        jButton34.setMinimumSize(new java.awt.Dimension(45, 60));
        jButton34.setPreferredSize(new java.awt.Dimension(45, 60));
        jButton34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton34ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(6, 3, 6, 3);
        jPanel1.add(jButton34, gridBagConstraints);

        jButton35.setIcon(new ImageIcon("./res/type_1/card_type_down/35.png"));
        jButton35.setMaximumSize(new java.awt.Dimension(45, 60));
        jButton35.setMinimumSize(new java.awt.Dimension(45, 60));
        jButton35.setPreferredSize(new java.awt.Dimension(45, 60));
        jButton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton35ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(6, 3, 6, 3);
        jPanel1.add(jButton35, gridBagConstraints);

        jButton36.setIcon(new ImageIcon("./res/type_1/card_type_down/36.png"));
        jButton36.setMaximumSize(new java.awt.Dimension(45, 60));
        jButton36.setMinimumSize(new java.awt.Dimension(45, 60));
        jButton36.setPreferredSize(new java.awt.Dimension(45, 60));
        jButton36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton36ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(6, 3, 6, 3);
        jPanel1.add(jButton36, gridBagConstraints);

        jButton37.setIcon(new ImageIcon("./res/type_1/card_type_down/37.png"));
        jButton37.setMaximumSize(new java.awt.Dimension(45, 60));
        jButton37.setMinimumSize(new java.awt.Dimension(45, 60));
        jButton37.setPreferredSize(new java.awt.Dimension(45, 60));
        jButton37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton37ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 8;
        gridBagConstraints.insets = new java.awt.Insets(6, 3, 6, 3);
        jPanel1.add(jButton37, gridBagConstraints);

        jButton38.setIcon(new ImageIcon("./res/type_1/card_type_down/38.png"));
        jButton38.setMaximumSize(new java.awt.Dimension(45, 60));
        jButton38.setMinimumSize(new java.awt.Dimension(45, 60));
        jButton38.setPreferredSize(new java.awt.Dimension(45, 60));
        jButton38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton38ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 8;
        gridBagConstraints.insets = new java.awt.Insets(6, 3, 6, 3);
        jPanel1.add(jButton38, gridBagConstraints);

        jButton39.setIcon(new ImageIcon("./res/type_1/card_type_down/39.png"));
        jButton39.setMaximumSize(new java.awt.Dimension(45, 60));
        jButton39.setMinimumSize(new java.awt.Dimension(45, 60));
        jButton39.setPreferredSize(new java.awt.Dimension(45, 60));
        jButton39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton39ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 8;
        gridBagConstraints.insets = new java.awt.Insets(6, 3, 6, 3);
        jPanel1.add(jButton39, gridBagConstraints);

        jButton40.setIcon(new ImageIcon("./res/type_1/card_type_down/40.png"));
        jButton40.setMaximumSize(new java.awt.Dimension(45, 60));
        jButton40.setMinimumSize(new java.awt.Dimension(45, 60));
        jButton40.setPreferredSize(new java.awt.Dimension(45, 60));
        jButton40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton40ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 8;
        gridBagConstraints.insets = new java.awt.Insets(6, 3, 6, 3);
        jPanel1.add(jButton40, gridBagConstraints);

        jButton41.setIcon(new ImageIcon("./res/type_1/card_type_down/41.png"));
        jButton41.setMaximumSize(new java.awt.Dimension(45, 60));
        jButton41.setMinimumSize(new java.awt.Dimension(45, 60));
        jButton41.setPreferredSize(new java.awt.Dimension(45, 60));
        jButton41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton41ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 8;
        gridBagConstraints.insets = new java.awt.Insets(6, 3, 6, 3);
        jPanel1.add(jButton41, gridBagConstraints);

        jButton42.setIcon(new ImageIcon("./res/type_1/card_type_down/42.png"));
        jButton42.setMaximumSize(new java.awt.Dimension(45, 60));
        jButton42.setMinimumSize(new java.awt.Dimension(45, 60));
        jButton42.setPreferredSize(new java.awt.Dimension(45, 60));
        jButton42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton42ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 8;
        gridBagConstraints.insets = new java.awt.Insets(6, 3, 6, 3);
        jPanel1.add(jButton42, gridBagConstraints);

        jButton43.setIcon(new ImageIcon("./res/type_1/card_type_down/43.png"));
        jButton43.setMaximumSize(new java.awt.Dimension(45, 60));
        jButton43.setMinimumSize(new java.awt.Dimension(45, 60));
        jButton43.setPreferredSize(new java.awt.Dimension(45, 60));
        jButton43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton43ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 8;
        gridBagConstraints.insets = new java.awt.Insets(6, 3, 6, 3);
        jPanel1.add(jButton43, gridBagConstraints);

        jButton44.setIcon(new ImageIcon("./res/type_1/card_type_down/44.png"));
        jButton44.setMaximumSize(new java.awt.Dimension(45, 60));
        jButton44.setMinimumSize(new java.awt.Dimension(45, 60));
        jButton44.setPreferredSize(new java.awt.Dimension(45, 60));
        jButton44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton44ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 8;
        gridBagConstraints.insets = new java.awt.Insets(6, 3, 6, 3);
        jPanel1.add(jButton44, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setMinimumSize(new java.awt.Dimension(100, 650));
        jPanel2.setPreferredSize(new java.awt.Dimension(100, 650));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jCheckBox1.setText("全选");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel2.add(jCheckBox1, gridBagConstraints);

        jCheckBox2.setText("万");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel2.add(jCheckBox2, gridBagConstraints);

        jCheckBox3.setText("饼");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel2.add(jCheckBox3, gridBagConstraints);

        jCheckBox4.setText("条");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel2.add(jCheckBox4, gridBagConstraints);

        jCheckBox5.setText("风");
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel2.add(jCheckBox5, gridBagConstraints);

        jCheckBox6.setText("三元");
        jCheckBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox6ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel2.add(jCheckBox6, gridBagConstraints);

        jCheckBox7.setText("花牌");
        jCheckBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox7ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel2.add(jCheckBox7, gridBagConstraints);

        jCheckBox8.setText("百搭");
        jCheckBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox8ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        jPanel2.add(jCheckBox8, gridBagConstraints);

        getContentPane().add(jPanel2, java.awt.BorderLayout.EAST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (!isButtonSelect1) {
            isButtonSelect1 = true;
            jButton1.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/1.jpg")); // NOI18N
        } else {
            isButtonSelect1 = false;
            jButton1.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/1.png")); // NOI18N
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (!isButtonSelect2) {
            isButtonSelect2 = true;
            jButton2.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/2.jpg")); // NOI18N
        } else {
            isButtonSelect2 = false;
            jButton2.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/2.png")); // NOI18N
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (!isButtonSelect3) {
            isButtonSelect3 = true;
            jButton3.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/3.jpg")); // NOI18N
        } else {
            isButtonSelect3 = false;
            jButton3.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/3.png")); // NOI18N
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (!isButtonSelect4) {
            isButtonSelect4 = true;
            jButton4.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/4.jpg")); // NOI18N
        } else {
            isButtonSelect4 = false;
            jButton4.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/4.png")); // NOI18N
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (!isButtonSelect5) {
            isButtonSelect5 = true;
            jButton5.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/5.jpg")); // NOI18N
        } else {
            isButtonSelect5 = false;
            jButton5.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/5.png")); // NOI18N
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if (!isButtonSelect6) {
            isButtonSelect6 = true;
            jButton6.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/6.jpg")); // NOI18N
        } else {
            isButtonSelect6 = false;
            jButton6.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/6.png")); // NOI18N
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if (!isButtonSelect7) {
            isButtonSelect7 = true;
            jButton7.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/7.jpg")); // NOI18N
        } else {
            isButtonSelect7 = false;
            jButton7.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/7.png")); // NOI18N
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if (!isButtonSelect8) {
            isButtonSelect8 = true;
            jButton8.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/8.jpg")); // NOI18N
        } else {
            isButtonSelect8 = false;
            jButton8.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/8.png")); // NOI18N
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        if (!isButtonSelect9) {
            isButtonSelect9 = true;
            jButton9.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/9.jpg")); // NOI18N
        } else {
            isButtonSelect9 = false;
            jButton9.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/9.png")); // NOI18N
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        if (!isButtonSelect10) {
            isButtonSelect10 = true;
            jButton10.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/10.jpg")); // NOI18N
        } else {
            isButtonSelect10 = false;
            jButton10.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/10.png")); // NOI18N
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        if (!isButtonSelect11) {
            isButtonSelect11 = true;
            jButton11.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/11.jpg")); // NOI18N
        } else {
            isButtonSelect11 = false;
            jButton11.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/11.png")); // NOI18N
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        if (!isButtonSelect12) {
            isButtonSelect12 = true;
            jButton12.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/12.jpg")); // NOI18N
        } else {
            isButtonSelect12 = false;
            jButton12.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/12.png")); // NOI18N
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        if (!isButtonSelect13) {
            isButtonSelect13 = true;
            jButton13.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/13.jpg")); // NOI18N
        } else {
            isButtonSelect13 = false;
            jButton13.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/13.png")); // NOI18N
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        if (!isButtonSelect14) {
            isButtonSelect14 = true;
            jButton14.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/14.jpg")); // NOI18N
        } else {
            isButtonSelect14 = false;
            jButton14.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/14.png")); // NOI18N
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        if (!isButtonSelect15) {
            isButtonSelect15 = true;
            jButton15.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/15.jpg")); // NOI18N
        } else {
            isButtonSelect15 = false;
            jButton15.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/15.png")); // NOI18N
        }
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        if (!isButtonSelect16) {
            isButtonSelect16 = true;
            jButton16.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/16.jpg")); // NOI18N
        } else {
            isButtonSelect16 = false;
            jButton16.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/16.png")); // NOI18N
        }
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        if (!isButtonSelect17) {
            isButtonSelect17 = true;
            jButton17.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/17.jpg")); // NOI18N
        } else {
            isButtonSelect17 = false;
            jButton17.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/17.png")); // NOI18N
        }
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        if (!isButtonSelect18) {
            isButtonSelect18 = true;
            jButton18.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/18.jpg")); // NOI18N
        } else {
            isButtonSelect18 = false;
            jButton18.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/18.png")); // NOI18N
        }
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        if (!isButtonSelect19) {
            isButtonSelect19 = true;
            jButton19.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/19.jpg")); // NOI18N
        } else {
            isButtonSelect19 = false;
            jButton19.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/19.png")); // NOI18N
        }
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        if (!isButtonSelect20) {
            isButtonSelect20 = true;
            jButton20.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/20.jpg")); // NOI18N
        } else {
            isButtonSelect20 = false;
            jButton20.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/20.png")); // NOI18N
        }
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        if (!isButtonSelect21) {
            isButtonSelect21 = true;
            jButton21.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/21.jpg")); // NOI18N
        } else {
            isButtonSelect21 = false;
            jButton21.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/21.png")); // NOI18N
        }
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        if (!isButtonSelect22) {
            isButtonSelect22 = true;
            jButton22.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/22.jpg")); // NOI18N
        } else {
            isButtonSelect22 = false;
            jButton22.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/22.png")); // NOI18N
        }
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        if (!isButtonSelect23) {
            isButtonSelect23 = true;
            jButton23.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/23.jpg")); // NOI18N
        } else {
            isButtonSelect23 = false;
            jButton23.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/23.png")); // NOI18N
        }
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        if (!isButtonSelect24) {
            isButtonSelect24 = true;
            jButton24.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/24.jpg")); // NOI18N
        } else {
            isButtonSelect24 = false;
            jButton24.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/24.png")); // NOI18N
        }
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        if (!isButtonSelect25) {
            isButtonSelect25 = true;
            jButton25.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/25.jpg")); // NOI18N
        } else {
            isButtonSelect25 = false;
            jButton25.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/25.png")); // NOI18N
        }
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        if (!isButtonSelect26) {
            isButtonSelect26 = true;
            jButton26.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/26.jpg")); // NOI18N
        } else {
            isButtonSelect26 = false;
            jButton26.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/26.png")); // NOI18N
        }
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        if (!isButtonSelect27) {
            isButtonSelect27 = true;
            jButton27.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/27.jpg")); // NOI18N
        } else {
            isButtonSelect27 = false;
            jButton27.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/27.png")); // NOI18N
        }
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
        if (!isButtonSelect28) {
            isButtonSelect28 = true;
            jButton28.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/28.jpg")); // NOI18N
        } else {
            isButtonSelect28 = false;
            jButton28.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/28.png")); // NOI18N
        }
    }//GEN-LAST:event_jButton28ActionPerformed

    private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed
        if (!isButtonSelect29) {
            isButtonSelect29 = true;
            jButton29.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/29.jpg")); // NOI18N
        } else {
            isButtonSelect29 = false;
            jButton29.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/29.png")); // NOI18N
        }
    }//GEN-LAST:event_jButton29ActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
        if (!isButtonSelect30) {
            isButtonSelect30 = true;
            jButton30.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/30.jpg")); // NOI18N
        } else {
            isButtonSelect30 = false;
            jButton30.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/30.png")); // NOI18N
        }
    }//GEN-LAST:event_jButton30ActionPerformed

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
        if (!isButtonSelect31) {
            isButtonSelect31 = true;
            jButton31.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/31.jpg")); // NOI18N
        } else {
            isButtonSelect31 = false;
            jButton31.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/31.png")); // NOI18N
        }
    }//GEN-LAST:event_jButton31ActionPerformed

    private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton32ActionPerformed
        if (!isButtonSelect32) {
            isButtonSelect32 = true;
            jButton32.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/32.jpg")); // NOI18N
        } else {
            isButtonSelect32 = false;
            jButton32.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/32.png")); // NOI18N
        }
    }//GEN-LAST:event_jButton32ActionPerformed

    private void jButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton33ActionPerformed
        if (!isButtonSelect33) {
            isButtonSelect33 = true;
            jButton33.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/33.jpg")); // NOI18N
        } else {
            isButtonSelect33 = false;
            jButton33.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/33.png")); // NOI18N
        }
    }//GEN-LAST:event_jButton33ActionPerformed

    private void jButton34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton34ActionPerformed
        if (!isButtonSelect34) {
            isButtonSelect34 = true;
            jButton34.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/34.jpg")); // NOI18N
        } else {
            isButtonSelect34 = false;
            jButton34.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/34.png")); // NOI18N
        }
    }//GEN-LAST:event_jButton34ActionPerformed

    private void jButton35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton35ActionPerformed
        if (!isButtonSelect35) {
            isButtonSelect35 = true;
            jButton35.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/35.jpg")); // NOI18N
        } else {
            isButtonSelect35 = false;
            jButton35.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/35.png")); // NOI18N
        }
    }//GEN-LAST:event_jButton35ActionPerformed

    private void jButton36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton36ActionPerformed
        if (!isButtonSelect36) {
            isButtonSelect36 = true;
            jButton36.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/36.jpg")); // NOI18N
        } else {
            isButtonSelect36 = false;
            jButton36.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/36.png")); // NOI18N
        }
    }//GEN-LAST:event_jButton36ActionPerformed

    private void jButton37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton37ActionPerformed
        if (!isButtonSelect37) {
            isButtonSelect37 = true;
            jButton37.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/37.jpg")); // NOI18N
        } else {
            isButtonSelect37 = false;
            jButton37.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/37.png")); // NOI18N
        }
    }//GEN-LAST:event_jButton37ActionPerformed

    private void jButton38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton38ActionPerformed
        if (!isButtonSelect38) {
            isButtonSelect38 = true;
            jButton38.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/38.jpg")); // NOI18N
        } else {
            isButtonSelect38 = false;
            jButton38.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/38.png")); // NOI18N
        }
    }//GEN-LAST:event_jButton38ActionPerformed

    private void jButton39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton39ActionPerformed
        if (!isButtonSelect39) {
            isButtonSelect39 = true;
            jButton39.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/39.jpg")); // NOI18N
        } else {
            isButtonSelect39 = false;
            jButton39.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/39.png")); // NOI18N
        }
    }//GEN-LAST:event_jButton39ActionPerformed

    private void jButton40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton40ActionPerformed
        if (!isButtonSelect40) {
            isButtonSelect40 = true;
            jButton40.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/40.jpg")); // NOI18N
        } else {
            isButtonSelect40 = false;
            jButton40.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/40.png")); // NOI18N
        }
    }//GEN-LAST:event_jButton40ActionPerformed

    private void jButton41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton41ActionPerformed
        if (!isButtonSelect41) {
            isButtonSelect41 = true;
            jButton41.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/41.jpg")); // NOI18N
        } else {
            isButtonSelect41 = false;
            jButton41.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/41.png")); // NOI18N
        }
    }//GEN-LAST:event_jButton41ActionPerformed

    private void jButton42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton42ActionPerformed
        if (!isButtonSelect42) {
            isButtonSelect42 = true;
            jButton42.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/42.jpg")); // NOI18N
        } else {
            isButtonSelect42 = false;
            jButton42.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/42.png")); // NOI18N
        }
    }//GEN-LAST:event_jButton42ActionPerformed

    private void jButton43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton43ActionPerformed
        if (!isButtonSelect43) {
            isButtonSelect43 = true;
            jButton43.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/43.jpg")); // NOI18N
        } else {
            isButtonSelect43 = false;
            jButton43.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/43.png")); // NOI18N
        }
    }//GEN-LAST:event_jButton43ActionPerformed

    private void jButton44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton44ActionPerformed
        if (!isButtonSelect44) {
            isButtonSelect44 = true;
            jButton44.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/44.jpg")); // NOI18N
        } else {
            isButtonSelect44 = false;
            jButton44.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/44.png")); // NOI18N
        }
    }//GEN-LAST:event_jButton44ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
		boolean b = true;
		if (jCheckBox1.isSelected()) {
			b = false;
		}
		isButtonSelect1 = b;
		isButtonSelect10 = b;
		isButtonSelect11 = b;
		isButtonSelect12 = b;
		isButtonSelect13 = b;
		isButtonSelect14 = b;
		isButtonSelect15 = b;
		isButtonSelect16 = b;
		isButtonSelect17 = b;
		isButtonSelect18 = b;
		isButtonSelect19 = b;
		isButtonSelect2 = b;
		isButtonSelect20 = b;
		isButtonSelect21 = b;
		isButtonSelect22 = b;
		isButtonSelect23 = b;
		isButtonSelect24 = b;
		isButtonSelect25 = b;
		isButtonSelect26 = b;
		isButtonSelect27 = b;
		isButtonSelect28 = b;
		isButtonSelect29 = b;
		isButtonSelect3 = b;
		isButtonSelect30 = b;
		isButtonSelect31 = b;
		isButtonSelect32 = b;
		isButtonSelect33 = b;
		isButtonSelect34 = b;
		isButtonSelect35 = b;
		isButtonSelect36 = b;
		isButtonSelect37 = b;
		isButtonSelect38 = b;
		isButtonSelect39 = b;
		isButtonSelect4 = b;
		isButtonSelect40 = b;
		isButtonSelect41 = b;
		isButtonSelect42 = b;
		isButtonSelect43 = b;
		isButtonSelect44 = b;
		isButtonSelect5 = b;
		isButtonSelect6 = b;
		isButtonSelect7 = b;
		isButtonSelect8 = b;
		isButtonSelect9 = b;
		jButton1ActionPerformed(null);
		jButton2ActionPerformed(null);
		jButton3ActionPerformed(null);
		jButton4ActionPerformed(null);
		jButton5ActionPerformed(null);
		jButton6ActionPerformed(null);
		jButton7ActionPerformed(null);
		jButton8ActionPerformed(null);
		jButton9ActionPerformed(null);
		jButton10ActionPerformed(null);
		jButton11ActionPerformed(null);
		jButton12ActionPerformed(null);
		jButton13ActionPerformed(null);
		jButton14ActionPerformed(null);
		jButton15ActionPerformed(null);
		jButton16ActionPerformed(null);
		jButton17ActionPerformed(null);
		jButton18ActionPerformed(null);
		jButton19ActionPerformed(null);
		jButton20ActionPerformed(null);
		jButton21ActionPerformed(null);
		jButton22ActionPerformed(null);
		jButton23ActionPerformed(null);
		jButton24ActionPerformed(null);
		jButton25ActionPerformed(null);
		jButton26ActionPerformed(null);
		jButton27ActionPerformed(null);
		jButton28ActionPerformed(null);
		jButton29ActionPerformed(null);
		jButton30ActionPerformed(null);
		jButton31ActionPerformed(null);
		jButton32ActionPerformed(null);
		jButton33ActionPerformed(null);
		jButton34ActionPerformed(null);
		jButton35ActionPerformed(null);
		jButton36ActionPerformed(null);
		jButton37ActionPerformed(null);
		jButton38ActionPerformed(null);
		jButton39ActionPerformed(null);
		jButton40ActionPerformed(null);
		jButton41ActionPerformed(null);
		jButton42ActionPerformed(null);
		jButton43ActionPerformed(null);
		jButton44ActionPerformed(null);
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
    	boolean b = true;
		if (jCheckBox2.isSelected()) {
			b = false;
		}
		isButtonSelect1 = b;
		isButtonSelect2 = b;
		isButtonSelect3 = b;
		isButtonSelect4 = b;
		isButtonSelect5 = b;
		isButtonSelect6 = b;
		isButtonSelect7 = b;
		isButtonSelect8 = b;
		isButtonSelect9 = b;
		jButton1ActionPerformed(null);
		jButton2ActionPerformed(null);
		jButton3ActionPerformed(null);
		jButton4ActionPerformed(null);
		jButton5ActionPerformed(null);
		jButton6ActionPerformed(null);
		jButton7ActionPerformed(null);
		jButton8ActionPerformed(null);
		jButton9ActionPerformed(null);
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
    	boolean b = true;
		if (jCheckBox3.isSelected()) {
			b = false;
		}
		isButtonSelect10 = b;
		isButtonSelect11 = b;
		isButtonSelect12 = b;
		isButtonSelect13 = b;
		isButtonSelect14 = b;
		isButtonSelect15 = b;
		isButtonSelect16 = b;
		isButtonSelect17 = b;
		isButtonSelect18 = b;
		jButton10ActionPerformed(null);
		jButton11ActionPerformed(null);
		jButton12ActionPerformed(null);
		jButton13ActionPerformed(null);
		jButton14ActionPerformed(null);
		jButton15ActionPerformed(null);
		jButton16ActionPerformed(null);
		jButton17ActionPerformed(null);
		jButton18ActionPerformed(null);
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
    	boolean b = true;
		if (jCheckBox4.isSelected()) {
			b = false;
		}
		isButtonSelect19 = b;
		isButtonSelect20 = b;
		isButtonSelect21 = b;
		isButtonSelect22 = b;
		isButtonSelect23 = b;
		isButtonSelect24 = b;
		isButtonSelect25 = b;
		isButtonSelect26 = b;
		isButtonSelect27 = b;
		jButton19ActionPerformed(null);
		jButton20ActionPerformed(null);
		jButton21ActionPerformed(null);
		jButton22ActionPerformed(null);
		jButton23ActionPerformed(null);
		jButton24ActionPerformed(null);
		jButton25ActionPerformed(null);
		jButton26ActionPerformed(null);
		jButton27ActionPerformed(null);
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
    	boolean b = true;
		if (jCheckBox5.isSelected()) {
			b = false;
		}
		isButtonSelect28 = b;
		isButtonSelect29 = b;
		isButtonSelect30 = b;
		isButtonSelect31 = b;
		jButton28ActionPerformed(null);
		jButton29ActionPerformed(null);
		jButton30ActionPerformed(null);
		jButton31ActionPerformed(null);
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void jCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox6ActionPerformed
    	boolean b = true;
		if (jCheckBox6.isSelected()) {
			b = false;
		}
		isButtonSelect32 = b;
		isButtonSelect33 = b;
		isButtonSelect34 = b;
		jButton32ActionPerformed(null);
		jButton33ActionPerformed(null);
		jButton34ActionPerformed(null);
    }//GEN-LAST:event_jCheckBox6ActionPerformed

    private void jCheckBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox7ActionPerformed
    	boolean b = true;
		if (jCheckBox7.isSelected()) {
			b = false;
		}
		isButtonSelect35 = b;
		isButtonSelect36 = b;
		isButtonSelect37 = b;
		isButtonSelect38 = b;
		isButtonSelect39 = b;
		isButtonSelect40 = b;
		isButtonSelect41 = b;
		isButtonSelect42 = b;
		jButton35ActionPerformed(null);
		jButton36ActionPerformed(null);
		jButton37ActionPerformed(null);
		jButton38ActionPerformed(null);
		jButton39ActionPerformed(null);
		jButton40ActionPerformed(null);
		jButton41ActionPerformed(null);
		jButton42ActionPerformed(null);
    }//GEN-LAST:event_jCheckBox7ActionPerformed

    private void jCheckBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox8ActionPerformed
    	boolean b = true;
		if (jCheckBox8.isSelected()) {
			b = false;
		}
		isButtonSelect43 = b;
		isButtonSelect44 = b;
		jButton43ActionPerformed(null);
		jButton44ActionPerformed(null);
    }//GEN-LAST:event_jCheckBox8ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
		String value = "";
		if (isButtonSelect1) {
			value += "1,";
		}
		if (isButtonSelect2) {
			value += "2,";
		}
		if (isButtonSelect3) {
			value += "3,";
		}
		if (isButtonSelect4) {
			value += "4,";
		}
		if (isButtonSelect5) {
			value += "5,";
		}
		if (isButtonSelect6) {
			value += "6,";
		}
		if (isButtonSelect7) {
			value += "7,";
		}
		if (isButtonSelect8) {
			value += "8,";
		}
		if (isButtonSelect9) {
			value += "9,";
		}
		if (isButtonSelect10) {
			value += "10,";
		}
		if (isButtonSelect11) {
			value += "11,";
		}
		if (isButtonSelect12) {
			value += "12,";
		}
		if (isButtonSelect13) {
			value += "13,";
		}
		if (isButtonSelect14) {
			value += "14,";
		}
		if (isButtonSelect15) {
			value += "15,";
		}
		if (isButtonSelect16) {
			value += "16,";
		}
		if (isButtonSelect17) {
			value += "17,";
		}
		if (isButtonSelect18) {
			value += "18,";
		}
		if (isButtonSelect19) {
			value += "19,";
		}
		if (isButtonSelect20) {
			value += "20,";
		}
		if (isButtonSelect21) {
			value += "21,";
		}
		if (isButtonSelect22) {
			value += "22,";
		}
		if (isButtonSelect23) {
			value += "23,";
		}
		if (isButtonSelect24) {
			value += "24,";
		}
		if (isButtonSelect25) {
			value += "25,";
		}
		if (isButtonSelect26) {
			value += "26,";
		}
		if (isButtonSelect27) {
			value += "27,";
		}
		if (isButtonSelect28) {
			value += "28,";
		}
		if (isButtonSelect29) {
			value += "29,";
		}
		if (isButtonSelect30) {
			value += "30,";
		}
		if (isButtonSelect31) {
			value += "31,";
		}
		if (isButtonSelect32) {
			value += "32,";
		}
		if (isButtonSelect33) {
			value += "33,";
		}
		if (isButtonSelect34) {
			value += "34,";
		}
		if (isButtonSelect35) {
			value += "35,";
		}
		if (isButtonSelect36) {
			value += "36,";
		}
		if (isButtonSelect37) {
			value += "37,";
		}
		if (isButtonSelect38) {
			value += "38,";
		}
		if (isButtonSelect39) {
			value += "39,";
		}
		if (isButtonSelect40) {
			value += "40,";
		}
		if (isButtonSelect41) {
			value += "41,";
		}
		if (isButtonSelect42) {
			value += "42,";
		}
		if (isButtonSelect43) {
			value += "43,";
		}
		if (isButtonSelect44) {
			value += "44,";
		}
		if (value.endsWith(",")) {
			value = value.substring(0, value.length() - 1);
		}
		parent.setXuanPai(value, type);
    }//GEN-LAST:event_formWindowClosed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

	public void initdata(String value) {
		String[] list = value.split(",");
		for (int i = 0; i < list.length; i++) {
			String key = list[i];
			if (key.equals("1")) {
				isButtonSelect1 = true;
				jButton1.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/1.jpg")); // NOI18N
			} else if (key.equals("2")) {
				isButtonSelect2 = true;
				jButton2.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/2.jpg")); // NOI18N
			} else if (key.equals("3")) {
				isButtonSelect3 = true;
				jButton3.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/3.jpg")); // NOI18N
			} else if (key.equals("4")) {
				isButtonSelect4 = true;
				jButton4.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/4.jpg")); // NOI18N
			} else if (key.equals("5")) {
				isButtonSelect5 = true;
				jButton5.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/5.jpg")); // NOI18N
			} else if (key.equals("6")) {
				isButtonSelect6 = true;
				jButton6.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/6.jpg")); // NOI18N
			} else if (key.equals("7")) {
				isButtonSelect7 = true;
				jButton7.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/7.jpg")); // NOI18N
			} else if (key.equals("8")) {
				isButtonSelect8 = true;
				jButton8.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/8.jpg")); // NOI18N
			} else if (key.equals("9")) {
				isButtonSelect9 = true;
				jButton9.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/9.jpg")); // NOI18N
			} else if (key.equals("10")) {
				isButtonSelect10 = true;
				jButton10.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/10.jpg")); // NOI18N
			} else if (key.equals("11")) {
				isButtonSelect11 = true;
				jButton11.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/11.jpg")); // NOI18N
			} else if (key.equals("12")) {
				isButtonSelect12 = true;
				jButton12.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/12.jpg")); // NOI18N
			} else if (key.equals("13")) {
				isButtonSelect13 = true;
				jButton13.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/13.jpg")); // NOI18N
			} else if (key.equals("14")) {
				isButtonSelect14 = true;
				jButton14.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/14.jpg")); // NOI18N
			} else if (key.equals("15")) {
				isButtonSelect15 = true;
				jButton15.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/15.jpg")); // NOI18N
			} else if (key.equals("16")) {
				isButtonSelect16 = true;
				jButton16.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/16.jpg")); // NOI18N
			} else if (key.equals("17")) {
				isButtonSelect17 = true;
				jButton17.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/17.jpg")); // NOI18N
			} else if (key.equals("18")) {
				isButtonSelect18 = true;
				jButton18.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/18.jpg")); // NOI18N
			} else if (key.equals("19")) {
				isButtonSelect19 = true;
				jButton19.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/19.jpg")); // NOI18N
			} else if (key.equals("20")) {
				isButtonSelect20 = true;
				jButton20.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/20.jpg")); // NOI18N
			} else if (key.equals("21")) {
				isButtonSelect21 = true;
				jButton21.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/21.jpg")); // NOI18N
			} else if (key.equals("22")) {
				isButtonSelect22 = true;
				jButton22.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/22.jpg")); // NOI18N
			} else if (key.equals("23")) {
				isButtonSelect23 = true;
				jButton23.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/23.jpg")); // NOI18N
			} else if (key.equals("24")) {
				isButtonSelect24 = true;
				jButton24.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/24.jpg")); // NOI18N
			} else if (key.equals("25")) {
				isButtonSelect25 = true;
				jButton25.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/25.jpg")); // NOI18N
			} else if (key.equals("26")) {
				isButtonSelect26 = true;
				jButton26.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/26.jpg")); // NOI18N
			} else if (key.equals("27")) {
				isButtonSelect27 = true;
				jButton27.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/27.jpg")); // NOI18N
			} else if (key.equals("28")) {
				isButtonSelect28 = true;
				jButton28.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/28.jpg")); // NOI18N
			} else if (key.equals("29")) {
				isButtonSelect29 = true;
				jButton29.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/29.jpg")); // NOI18N
			} else if (key.equals("30")) {
				isButtonSelect30 = true;
				jButton30.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/30.jpg")); // NOI18N
			} else if (key.equals("31")) {
				isButtonSelect31 = true;
				jButton31.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/31.jpg")); // NOI18N
			} else if (key.equals("32")) {
				isButtonSelect32 = true;
				jButton32.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/32.jpg")); // NOI18N
			} else if (key.equals("33")) {
				isButtonSelect33 = true;
				jButton33.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/33.jpg")); // NOI18N
			} else if (key.equals("34")) {
				isButtonSelect34 = true;
				jButton34.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/34.jpg")); // NOI18N
			} else if (key.equals("35")) {
				isButtonSelect35 = true;
				jButton35.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/35.jpg")); // NOI18N
			} else if (key.equals("36")) {
				isButtonSelect36 = true;
				jButton36.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/36.jpg")); // NOI18N
			} else if (key.equals("37")) {
				isButtonSelect37 = true;
				jButton37.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/37.jpg")); // NOI18N
			} else if (key.equals("38")) {
				isButtonSelect38 = true;
				jButton38.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/38.jpg")); // NOI18N
			} else if (key.equals("39")) {
				isButtonSelect39 = true;
				jButton39.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/39.jpg")); // NOI18N
			} else if (key.equals("40")) {
				isButtonSelect40 = true;
				jButton40.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/40.jpg")); // NOI18N
			} else if (key.equals("41")) {
				isButtonSelect41 = true;
				jButton41.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/41.jpg")); // NOI18N
			} else if (key.equals("42")) {
				isButtonSelect42 = true;
				jButton42.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/42.jpg")); // NOI18N
			} else if (key.equals("43")) {
				isButtonSelect43 = true;
				jButton43.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/43.jpg")); // NOI18N
			} else if (key.equals("44")) {
				isButtonSelect44 = true;
				jButton44.setIcon(new javax.swing.ImageIcon("./res/type_1/card_type_down/44.jpg")); // NOI18N
			}
		}
	}
}
